# Generated by Django 2.2.1 on 2019-12-26 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20191226_1444'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
